### ISSUE TITLE
Checklist for Pangeo / Coiled Webinar (Feb TDA)

### ISSUE THREAD

**Issue by rabernat** [ocean-transport/coiled_collaboration#18]
- [ ] Reproducible reproducers of performance improvements
  - [ ] xhistogram (internal refactoring to use dask better)
  - [ ] xgcm (internal refactoring to use dask better - https://github.com/xgcm/xgcm/issues/344)
  - [ ] array groupby (Deepak)
  - [ ] Dask memory management
- [ ] Blog post - https://medium.com/pangeo/an-open-source-success-story-f8c4e5b246c0
- [ ] Slide deck
- [ ] Future work
  - Active memory management - https://coiled.io/blog/introducing-the-dask-active-memory-manager/
  - Implement grid_ufunc protocols
  - How to take advantage of dask APIs for advanced usage (Array Groupby)
  - Recommendations for academic research to interact with open source
- [ ] Event abstract (logistics)
- [ ] Headshots / bios
